// Auto-generated by deploy.js
// Do not edit manually

export const CONTRACTS = {
  waitToken: {
    address: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
    chainId: 31337
  },
  tokenSale: {
    address: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
    chainId: 31337
  },
  waitingList: {
    address: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",  // Proxy address (users interact with this)
    implementationAddress: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",  // Implementation address
    chainId: 31337
  }
};

export const NETWORK_CONFIG = {
  chainId: 31337,
  name: "localhost",
  rpcUrl: "http://127.0.0.1:8545"
};
